export const env = {
    MONGODB_URI: process.env.NEXT_PUBLIC_MONGODB_URI,
    DATABASE_NAME: process.env.NEXT_PUBLIC_DATABASE_NAME,
    HOST: process.env.NEXT_PUBLIC_API_HOST,
    API_HOST: process.env.NEXT_PUBLIC_API_HOST,
    API_KEY_SENDINBLUE: process.env.NEXT_PUBLIC_API_KEY_SENDINBLUE,
}